services:
  auth-server:
    build: ./auth-server
    image: microservices-auth-server:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

  api-gateway:
    build: ./api-gateway
    image: microservices-api-gateway:latest
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - auth-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker # <--- Aktiverar 'docker'-profilen för Docker Compose
      # Kontrollerar även server.port i application-docker.properties.
      # Om API Gateway ska lyssna på 8081 i Docker Compose,
      # application-docker.properties måste ha server.port=8081.
      # Docker-compose.yaml har 8081:8081, så det matchar.
      # k8s-deployment har 8080:8080, så då måste application-kubernetes.properties ha server.port=8080.

  joke-service:
    build: ./joke-service
    image: microservices-joke-service:latest
    networks:
      - my-network

  quote-service:
    build: ./quote-service
    image: microservices-quote-service:latest
    networks:
      - my-network

networks:
  my-network:
    driver: bridge