services:
  auth-server:
    build: ./auth-server
    image: microservices-auth-server:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

  api-gateway:
    build: ./api-gateway
    image: microservices-api-gateway:latest
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - auth-server

  joke-service:
    build: ./joke-service
    image: microservices-joke-service:latest
    networks:
      - my-network

  quote-service:
    build: ./quote-service
    image: microservices-quote-service:latest
    networks:
      - my-network

networks:
  my-network:
    driver: bridge