services:
  auth-server:
    build: ./auth-server
    image: microservices-auth-server:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

  api-gateway:
    build: ./api-gateway
    image: microservices-api-gateway:latest
    ports:
      - "8081:8081" # Notera att du använder 8081 här, inte 8080 som i k8s
    networks:
      - my-network
    depends_on:
      - auth-server
    environment: # <--- LÄGG TILL DENNA BLOCKET
      - SPRING_PROFILES_ACTIVE=docker # <--- Aktivera 'docker'-profilen för Docker Compose
      # Kontrollera även din server.port i application-docker.properties.
      # Om din API Gateway ska lyssna på 8081 i Docker Compose,
      # måste din application-docker.properties ha server.port=8081.
      # Din docker-compose.yaml har 8081:8081, så det matchar.
      # Din k8s-deployment har 8080:8080, så då måste application-kubernetes.properties ha server.port=8080.

  joke-service:
    build: ./joke-service
    image: microservices-joke-service:latest
    networks:
      - my-network

  quote-service:
    build: ./quote-service
    image: microservices-quote-service:latest
    networks:
      - my-network

networks:
  my-network:
    driver: bridge